### ISSUE TITLE
Standalone Selenoid doesn't use --port from config.json file

### ISSUE THREAD

**Issue by ElijahCapricorn** [aerokube/selenoid#243] opened 2017-10-18 08:28 UTC
Selenoid v1.3.8

config.json:
```
"internet explorer": {
  "default": "11",
  "versions": {
    "11": {
      "image": ["C:\\IEDriverServer.exe", "--log-level=DEBUG", "--port=17556"]
    }
  }
}
```

Run: `selenoid_windows_amd64.exe -disable-docker -conf config.json -limit 1`

Actual result from console log: `[STARTING_PROCESS] [[C:\IEDriverServer.exe --log-level=DEBUG --port=17556 --port=33734]]`

Expected result:` [STARTING_PROCESS] [[C:\IEDriverServer.exe --log-level=DEBUG --port=17556]]`

**Comment by vania-pooh** [comment] 2017-10-18 08:33
@ElijahCapricorn this is the expected behavior. When working with drivers directly Selenoid allocates a free port itself and appends `--port` argument automatically. When running multiple tests in parallel specifying a fixed port value will lead to session startup errors because only one driver process will be able to allocate port from config.

**Comment by ElijahCapricorn** [comment] 2017-10-18 08:40
@vania-pooh I see. But it looks strange that both parameters are passed to the driver.

**Comment by vania-pooh** [comment] 2017-10-18 08:59
@ElijahCapricorn we expect that you do not specify `--port` manually.

**Comment by vania-pooh** [comment] 2017-10-21 17:19
@ElijahCapricorn any more questions in this issue?

**Comment by ElijahCapricorn** [comment] 2017-10-24 11:59
@vania-pooh No, I just noticed this when setup selenoid. I think we can close the issue if it is an expected behavior.

**Comment by vania-pooh** [comment] 2017-10-24 14:41
Closing then.

**Closed by vania-pooh** 2017-10-24 14:41 UTC
