### ISSUE TITLE
Docker client library version in selenoid latest?

### ISSUE THREAD

**Issue by dothebart** [aerokube/selenoid#1422] opened 2024-05-15 10:29 UTC
Hi, 
I'm using the latest selenoid, however recently I'm getting: 
```
2024/05/15 10:10:53 [-] [NEW_REQUEST] [unknown] [192.168.100.68]
2024/05/15 10:10:53 [-] [NEW_REQUEST_ACCEPTED] [unknown] [192.168.100.68]
2024/05/15 10:10:53 [7] [LOCATING_SERVICE] [chrome] []
2024/05/15 10:10:53 [-] [DEFAULT_VERSION] [Using default version: latest]
2024/05/15 10:10:53 [7] [USING_DOCKER] [chrome] [latest]
2024/05/15 10:10:53 [7] [CREATING_CONTAINER] [selenoid/chrome]
2024/05/15 10:10:53 [7] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: {"message":"client version 1.12 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version"}]
```
in the logs which probably indicates that the selenoid linked docker client library is to old for my local docker? 

```
dpkg --list |grep -i docker 
ii  docker-buildx-plugin                             0.14.0-1~debian.12~bookworm               amd64        Docker Buildx cli plugin.
ii  docker-ce                                        5:26.1.2-1~debian.12~bookworm             amd64        Docker: the open-source application container engine
ii  docker-ce-cli                                    5:26.1.2-1~debian.12~bookworm             amd64        Docker CLI: the open-source application container engine
ii  docker-compose                                   1.29.2-6                                  all          define and run multi-container Docker applications with YAML
ii  python3-compose                                  1.29.2-6                                  all          Python implementation of docker-compose file specification
ii  python3-docker                                   6.1.3-0.1                                 all          Python 3 wrapper to access docker.io's control socket
ii  python3-dockerpty                                0.4.1-5                                   all          Pseudo-tty handler for docker Python client (Python 3.x)

docker --version
Docker version 26.1.2, build 211e74b

```
is my system. 
Can you please confirm whether `1.12` is the library version inside selenoid? since I didn't find anything else with that version.

**Comment by vania-pooh** [comment] 2024-05-18 14:46
@dothebart this is a duplicate of https://github.com/aerokube/selenoid/issues/1420

**Closed by vania-pooh** 2024-05-18 14:46 UTC

**Comment by dothebart** [comment] 2024-05-21 06:46
Thanks for clarifying.
