### ISSUE TITLE
Selenoid session failing after upgrade to Docker 23.0.4

### ISSUE THREAD

**Issue by Zsmith32** [aerokube/selenoid#1333] opened 2023-04-22 01:33 UTC
Hello! We seem to be having issues with selenoid retrieving the IPs for the browser containers after upgrading to docker 23.0.4

We're running selenoid:1.10.9
OS ubuntu 20.04
Docker 23.0.4

 

[17:00:52 e2e test test-ci] Error: Failed to create session.[0m
[17:00:52 e2e test test-ci] New session attempts retry count exceeded[0m
[17:00:52 e2e test test-ci] [0m
[17:00:52 e2e test test-ci] Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible

[17:09:06 end][2023-04-19T20:54:12.206621040Z 2023/04/19 20:54:12 [-] [INIT] [Loading configuration files...][0m
[17:09:06 end][2023-04-19T20:54:12.207123014Z 2023/04/19 20:54:12 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json][0m
[17:09:06 end][2023-04-19T20:54:12.207672405Z 2023/04/19 20:54:12 [-] [INIT] [Video Dir: /opt/selenoid/video][0m
[17:09:06 end][2023-04-19T20:54:12.207737361Z 2023/04/19 20:54:12 [-] [INIT] [Logs Dir: /opt/selenoid/logs][0m
[17:09:06 end][2023-04-19T20:54:12.461472825Z 2023/04/19 20:54:12 [-] [INIT] [Did not manage to determine your Docker API version - using default version: 1.41][0m
[17:09:06 end][2023-04-19T20:54:12.461510705Z 2023/04/19 20:54:12 [-] [INIT] [Timezone: UTC][0m
[17:09:06 end][2023-04-19T20:54:12.461515568Z 2023/04/19 20:54:12 [-] [INIT] [Listening on 0.0.0.0:4444][0m
[17:09:06 end][2023-04-19T20:58:37.979260797Z 2023/04/19 20:58:37 [-] [NEW_REQUEST] [unknown] [172.21.0.3][0m
[17:09:06 end][2023-04-19T20:58:37.979310816Z 2023/04/19 20:58:37 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.21.0.3][0m
[17:09:06 end][2023-04-19T20:58:37.979584322Z 2023/04/19 20:58:37 [0] [LOCATING_SERVICE] [firefox] [][0m
[17:09:06 end][2023-04-19T20:58:37.979605068Z 2023/04/19 20:58:37 [-] [DEFAULT_VERSION] [Using default version: 110.0][0m
[17:09:06 end][2023-04-19T20:58:37.979609214Z 2023/04/19 20:58:37 [0] [USING_DOCKER] [firefox] [110.0][0m
[17:09:06 end][2023-04-19T20:58:37.979612463Z 2023/04/19 20:58:37 [0] [CREATING_CONTAINER] [<private-repo>/selenoid/firefox:110.0][0m
[17:09:06 end][2023-04-19T20:58:37.995683485Z 2023/04/19 20:58:37 [-] [NEW_REQUEST] [unknown] [172.21.0.3][0m
[17:09:06 end][2023-04-19T20:58:37.995710307Z 2023/04/19 20:58:37 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.21.0.3][0m
[17:09:06 end][2023-04-19T20:58:37.995715983Z 2023/04/19 20:58:37 [1] [LOCATING_SERVICE] [firefox] [][0m
[17:09:06 end][2023-04-19T20:58:37.995720887Z 2023/04/19 20:58:37 [-] [DEFAULT_VERSION] [Using default version: 110.0][0m
[17:09:06 end][2023-04-19T20:58:37.995725667Z 2023/04/19 20:58:37 [1] [USING_DOCKER] [firefox] [110.0][0m
[17:09:06 end][2023-04-19T20:58:37.995730260Z 2023/04/19 20:58:37 [1] [CREATING_CONTAINER] [<private-repo>/selenoid/firefox:110.0][0m
[17:09:06 end][2023-04-19T20:58:38.023188464Z 2023/04/19 20:58:38 [-] [NEW_REQUEST] [unknown] [172.21.0.3][0m
[17:09:06 end][2023-04-19T20:58:38.023212032Z 2023/04/19 20:58:38 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.21.0.3][0m
[17:09:06 end][2023-04-19T20:58:38.023291119Z 2023/04/19 20:58:38 [2] [LOCATING_SERVICE] [firefox] [][0m
[17:09:06 end][2023-04-19T20:58:38.023309455Z 2023/04/19 20:58:38 [-] [DEFAULT_VERSION] [Using default version: 110.0][0m
[17:09:06 end][2023-04-19T20:58:38.023313278Z 2023/04/19 20:58:38 [2] [USING_DOCKER] [firefox] [110.0][0m
[17:09:06 end][2023-04-19T20:58:38.023316397Z 2023/04/19 20:58:38 [2] [CREATING_CONTAINER] [<private-repo>/selenoid/firefox:110.0][0m
[17:09:06 end][2023-04-19T20:58:38.026503292Z 2023/04/19 20:58:38 [0] [STARTING_CONTAINER] [<private-repo>/selenoid/firefox:110.0] [541449069a58e32963d00c03e8ada34a830186e8a8afaba9c9f9b245f0f54f6e][0m
[17:09:06 end][2023-04-19T20:58:38.026522614Z 2023/04/19 20:58:38 [1] [STARTING_CONTAINER] [<private-repo>/selenoid/firefox:110.0] [c5f38147544455efb079851d61bcbcf66e3e95feae2165f8420722616e69c71e][0m
[17:09:06 end][2023-04-19T20:58:38.053041231Z 2023/04/19 20:58:38 [-] [NEW_REQUEST] [unknown] [172.21.0.3][0m
[17:09:06 end][2023-04-19T20:58:38.053076634Z 2023/04/19 20:58:38 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.21.0.3][0m
[17:09:06 end][2023-04-19T20:58:38.053102937Z 2023/04/19 20:58:38 [3] [LOCATING_SERVICE] [firefox] [][0m
[17:09:06 end][2023-04-19T20:58:38.053109369Z 2023/04/19 20:58:38 [-] [DEFAULT_VERSION] [Using default version: 110.0][0m
[17:09:06 end][2023-04-19T20:58:38.053115018Z 2023/04/19 20:58:38 [3] [USING_DOCKER] [firefox] [110.0][0m
[17:09:06 end][2023-04-19T20:58:38.053118740Z 2023/04/19 20:58:38 [3] [CREATING_CONTAINER] [<private-repo>/selenoid/firefox:110.0][0m
[17:09:06 end][2023-04-19T20:58:38.096190278Z 2023/04/19 20:58:38 [2] [STARTING_CONTAINER] [<private-repo>/selenoid/firefox:110.0] [ba1e881903dcb90c573ab569fd2d2c9c764be474e81408cfdeb4f15b03ca0370][0m
[17:09:06 end][2023-04-19T20:58:38.103941253Z 2023/04/19 20:58:38 [3] [STARTING_CONTAINER] [<private-repo>/selenoid/firefox:110.0] [602686a18bd3b16c0afcc1785d49e42c1036f399a143f539bc829c5a490e8eb6][0m
[17:09:06 end][2023-04-19T20:58:38.572327550Z 2023/04/19 20:58:38 [0] [CONTAINER_STARTED] [<private-repo>/selenoid/firefox:110.0] [541449069a58e32963d00c03e8ada34a830186e8a8afaba9c9f9b245f0f54f6e] [0.55s][0m
[17:09:06 end][2023-04-19T20:58:38.576121274Z 2023/04/19 20:58:38 [0] [SERVICE_STARTED] [<private-repo>/selenoid/firefox:110.0] [541449069a58e32963d00c03e8ada34a830186e8a8afaba9c9f9b245f0f54f6e] [0.00s][0m
[17:09:06 end][2023-04-19T20:58:38.576143310Z 2023/04/19 20:58:38 [0] [PROXY_TO] [541449069a58e32963d00c03e8ada34a830186e8a8afaba9c9f9b245f0f54f6e] [ [http://:4444/wd/hub][0m](http://:4444/wd/hub%5d%5b0m)
[17:09:06 end][2023-04-19T20:58:38.576249943Z 2023/04/19 20:58:38 [0] [SESSION_ATTEMPTED] [ http://:4444/wd/hub] [1][0m
[17:09:06 end][2023-04-19T20:58:38.576359700Z 2023/04/19 20:58:38 [-] [NEW_REQUEST] [unknown] [127.0.0.1][0m
[17:09:06 end][2023-04-19T20:58:38.576388610Z 2023/04/19 20:58:38 [-] [NEW_REQUEST_ACCEPTED] [unknown] [127.0.0.1][0m
[17:09:06 end][2023-04-19T20:58:38.576514881Z 2023/04/19 20:58:38 [4] [LOCATING_SERVICE] [firefox] [][0m
[17:09:06 end][2023-04-19T20:58:38.576529527Z 2023/04/19 20:58:38 [-] [DEFAULT_VERSION] [Using default version: 110.0][0m
[17:09:06 end][2023-04-19T20:58:38.576535472Z 2023/04/19 20:58:38 [4] [USING_DOCKER] [firefox] [110.0][0m
[17:09:06 end][2023-04-19T20:58:38.576538811Z 2023/04/19 20:58:38 [4] [CREATING_CONTAINER] [<private-repo>/selenoid/firefox:110.0][0m
[17:09:06 end][2023-04-19T20:58:38.593058105Z 2023/04/19 20:58:38 [4] [STARTING_CONTAINER] [<private-repo>/selenoid/firefox:110.0] [4f59021563178f9726b7eaf6148cf33f08f506349a5f96c870878ab432a0af52][0m
[17:09:06 end][2023-04-19T20:58:38.866208572Z 2023/04/19 20:58:38 [2] [CONTAINER_STARTED] [<private-repo>/selenoid/firefox:110.0] [ba1e881903dcb90c573ab569fd2d2c9c764be474e81408cfdeb4f15b03ca0370] [0.77s][0m
[17:09:06 end][2023-04-19T20:58:38.867263680Z 2023/04/19 20:58:38 [2] [SERVICE_STARTED] [<private-repo>/selenoid/firefox:110.0] [ba1e881903dcb90c573ab569fd2d2c9c764be474e81408cfdeb4f15b03ca0370] [0.00s][0m
[17:09:06 end] 2023-04-19T20:58:38.867276561Z 2023/04/19 20:58:38 [2] [PROXY_TO] [ba1e881903dcb90c573ab569fd2d2c9c764be474e81408cfdeb4f15b03ca0370] [ [http://:4444/wd/hub][0m](http://:4444/wd/hub%5d%5b0m)

We're unable to pull 1.10.10 or 1.10.11 from our private repo atm because it doesn't support OCI images, so if those versions can handle the new docker version sorry for repease issue. But posting here in case it hasn't been addressed yet.

**Comment by vania-pooh** [comment] 2023-04-23 01:37
@Zsmith32 try latest Selenoid release (e.g. 1.10.11), where Docker client was updated to the latest version.

**Comment by subsan** [comment] 2023-05-18 14:24
I have the same problem with docker 24.0.0 ([PROXY_TO].... [http://:4444/wd/hub] (with out ip)) now
Downgrade docker to 23.0.6 solve the problem

**Comment by vania-pooh** [comment] 2023-05-18 18:02
@subsan show me `docker version` output.

**Comment by subsan** [comment] 2023-05-18 19:00
> @subsan show me `docker version` output.

![image](https://github.com/aerokube/selenoid/assets/1093589/4a68d742-dfd1-4e4a-aaab-a0e5eea4f7bd)

**Comment by vania-pooh** [comment] 2023-05-19 08:59
@subsan ok, this is a duplicate of #1340. This is planned for the next release.

**Closed by vania-pooh** 2023-05-19 08:59 UTC
