### ISSUE TITLE
How to prevent popping-up xdg-open dialog?

### ISSUE THREAD

**Issue by cjmme** [aerokube/selenoid#1094] opened 2021-04-23 05:43 UTC
I am running test by Selenoid, when I open a link on the Chrome , it will pop up xdg-open dialog, we are using the chrome image crated by selenoid team, how to config to prevent the xdg-open?

**Comment by vania-pooh** [comment] 2021-04-25 06:14
Duplicate of #1069.

**Closed by vania-pooh** 2021-04-25 06:14 UTC
