### ISSUE TITLE
Only legacy OSS protocol dialect is supported

### ISSUE THREAD

**Issue by RouR** [aerokube/selenoid#855] opened 2020-01-03 15:03 UTC
I have issue with library [Selenium.WebDriver 4.0.0-alpha03](https://www.nuget.org/packages/Selenium.WebDriver/4.0.0-alpha03)

This lib is not campatible with selenoid 1.9.3 after removing legacy OSS protocol dialect - check this commit https://github.com/SeleniumHQ/selenium/commit/8767cd3d3a5258387d0b1cda86d3b024929def2f#diff-5fedfeb3060c9b589bc5ac90334761caL1073

This appears as error

> {"status":13,"value":{"message":"Requested environment is not available"}}

**Comment by vania-pooh** [comment] 2020-01-04 06:08
@RouR that means you are specifying capabilities incorrectly. Could you please show your capabilities?

**Comment by RouR** [comment] 2020-01-04 08:23
```
var browser = new ChromeOptions();
browser.BrowserVersion = "79";
var driver = new RemoteWebDriver(options.HubUrl, browser.ToCapabilities(), options.BrowserTimeout);
```
This code is ok with Selenium.WebDriver 3.141.0

**Comment by vania-pooh** [comment] 2020-01-04 17:34
@RouR Selenoid supports w3c-style protocol. Anyway, give me some time to check (will do with Java client of the same version, have no C#).

**Comment by vania-pooh** [comment] 2020-01-09 04:59
@RouR for me just the same version of Java client works like a charm. Please try to print request and response body:
```
CommandExecutor commandExecutor = new HttpCommandExecutor(...);
WebDriver driver = new RemoteWebDriver(commandExecutor, browser);
```
I'm not a C# developer, so there should be the way to make .NET standard library print JSON request and response body. So far as I can see in [this](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Remote/HttpCommandExecutor.cs) class Selenium is using standard `System.Net.Http` package to make HTTP requests.

**Comment by RouR** [comment] 2020-01-09 08:42
This work:
```
{"desiredCapabilities":{"browserName":"chrome","browserVersion":"79","goog:chromeOptions":{"args":[]}},"capabilities":{"firstMatch":[{"browserName":"chrome","browserVersion":"79","goog:chromeOptions":{"args":["--enable-dom-distiller","--distillability-dev"],"localState":{"reader.parse-on-load.enabled":true}}}]}}
```

```

{"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"79.0.3945.79","chrome":{"chromedriverVersion":"79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614})","userDataDir":"/tmp/.com.google.Chrome.WzrN4V"},"goog:chromeOptions":{"debuggerAddress":"localhost:40617"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"linux","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"},"sessionId":"f8d46813f4b203e76f6cfea31ec7cd37"}}
```

This not work:
```
{"capabilities":{"firstMatch":[{"browserName":"chrome","browserVersion":"79","goog:chromeOptions":{"args":[]}}]}}
```

```
{"status":13,"value":{"message":"Requested environment is not available"}}
```

See missed [desiredCapabilities](https://github.com/SeleniumHQ/selenium/commit/8767cd3d3a5258387d0b1cda86d3b024929def2f#diff-5fedfeb3060c9b589bc5ac90334761caL1073)

**Comment by vania-pooh** [comment] 2020-01-09 08:46
@RouR ok, then this is because of missing `firstMatch` support in Selenoid. Closing this as a duplicate of https://github.com/aerokube/selenoid/issues/450.

**Closed by vania-pooh** 2020-01-09 08:46 UTC

**Comment by vania-pooh** [comment] 2020-01-14 04:18
@RouR yesterday we merged support for `firstMatch`. Could you try whether it works with `aerokube/selenoid:latest` image?

**Comment by RouR** [comment] 2020-01-14 10:25
Yes, it work!
Thanks a lot

**Comment by vania-pooh** [comment] 2020-01-14 10:27
@RouR ok, this will be released during next days.
