### ISSUE TITLE
Inevitable SESSION_TIMED_OUT after using "/download" API

### ISSUE THREAD

**Issue by andrii-rymar** [aerokube/selenoid#1136] opened 2021-08-30 11:44 UTC
`/download` API usage causes SESSION_TIMED_OUT to be fired after session timeout even if we actually send commands during that time.

Simple test to reproduce the issue:
1. Set session timeout for 3 minutes
2. Open any website
3. List downloaded files via Selenoid API GET /download/:session_id/?json
4. Loop page refresh for 4 minutes with few seconds interval

After 3 minutes Selenoid reports SESSION_TIMED_OUT deleting the session afterwards despite we sent browser commands all that time.

Versions affected: 1.10.3-1.10.4, not present in 1.10.1.

**Comment by vania-pooh** [comment] 2021-08-30 11:47
@andrii-rymar should have been fixed in 1.10.2, but we'll check.

**Comment by andrii-rymar** [comment] 2021-09-02 11:54
Probably the same as #1112

**Comment by vania-pooh** [comment] 2021-09-06 10:53
Yes, that's a duplicate of #1112, which was fixed now.

**Closed by vania-pooh** 2021-09-06 10:53 UTC
Labels: bug
