### ISSUE TITLE
Is windows os chrome really different from linux？

### ISSUE THREAD

**Issue by izachwei** [aerokube/selenoid#1283] opened 2022-11-23 01:22 UTC
Hi ,
I have a question. Does installing vm in docker container, Virtual windows system really bring value?Is there really a difference between linux and windows chrome

I hope you can answer that. Thank you very much

**Comment by vania-pooh** [comment] 2022-11-23 07:09
Duplicate of https://github.com/aerokube/windows-images/issues/44.

**Closed by vania-pooh** 2022-11-23 07:09 UTC
