### ISSUE TITLE
No documentation for how to use Selenium's chrome dev tools

### ISSUE THREAD

**Issue by neilcronin** [aerokube/selenoid#1217] opened 2022-05-07 06:18 UTC
Selenium documents how to use chrome dev tools as part of a test, but running the test against a Selenoid grid fails with 

```
org.openqa.selenium.devtools.DevToolsException: Unable to create DevTools connection
```

The Selenium documentation: https://www.selenium.dev/documentation/webdriver/bidirectional/chrome_devtools/

The selenium/jvm code I am using is:

```
        val driver = RemoteWebDriver(URL("http://$seleniumGridHostname:4444/wd/hub"), options)
        val devTools = (Augmenter().augment(driver) as HasDevTools).devTools
        devTools.createSession()
        devTools.send(Emulation.setTimezoneOverride("Asia/Tokyo"))
```

There is no documentation in Selenoid that I could find about how to use this feature, or stating that it is not possible.  

This feature works with a vanilla Selenium grid, so I expect it should work with Selenoid, or that there is documentation about how to achieve the same thing in another way.

Thanks!

**Comment by vania-pooh** [comment] 2022-05-10 05:42
@neilcronin there is no documentation because this is not supported. This is a duplicate of #1146.

**Closed by vania-pooh** 2022-05-10 05:42 UTC
