### ISSUE TITLE
Cannot find se:cdp capability for RemoteWebDriver

### ISSUE THREAD

**Issue by Dor-bl** [aerokube/selenoid#1146] opened 2021-10-14 05:10 UTC
Hi,

I'm trying to add DevtoolsSession to the remote driver instance, but when I do I get the below exception: 
"Cannot find se:cdp capability for driver"

Is it something on selenoid side or the selenium project?

` ChromeOptions dockerChromoptions = new ChromeOptions();
          
                    Dictionary<string, object> selenoidOptions = new Dictionary<string, object>
                    {
                        {"name", testGlobalParams.TestName },
                        { "enableLog", false },
                        { "logName", testGlobalParams.TestName + ".log" },
                        { "enableVNC", true }
                    };
                    dockerChromoptions.AddAdditionalOption("selenoid:options", selenoidOptions);
                      
                    try
                    {
                        RemoteWebDriver dockerChromeDriver = new RemoteWebDriver(new Uri(DockerPort), dockerChromoptions.ToCapabilities(), remoteDriverTimeOut);
                        devToolssession = dockerChromeDriver.GetDevToolsSession();`

ENV:
C# .Net
Selenium.WebDriver 4.0 RC3 
Selenium.Support 4.0 RC3 
Selenoid:1.10.5

**Comment by Dor-bl** [comment] 2021-10-14 07:27
@vania-pooh I will try to contact the Selenium .NET contributors, l assume issue is on their side then

**Comment by Dor-bl** [comment] 2021-10-14 07:59
@vania-pooh I got an answer from Selenium maintainer that it should work Grid 4, so any chance we can make it happen for selenoid as well?

**Comment by vania-pooh** [comment] 2021-10-14 13:25
@Dor-bl I think there should be a class that allows to create a Devtools session without passing this capability. An example project demonstrating devtools features is shown here: https://github.com/aerokube/chrome-developer-tools-protocol-java-example

**Comment by doctor-house** [comment] 2021-10-14 15:37
@vania-pooh this is not a capability you pass into the session but one that is returned from session creation in selenium 4. The selenium 4 client expects `se:cdp` and `se:cdpVersion` to be returned by the session capabilities in order for devtools to work. I think selenoid could easily support this by returning `ws://selenoid.example.com:4444/devtools/<session-id>` as `se:cdp` and the browser version as `se:cdpVersion`. Should be noted that selenium 4 was [officially released yesterday.](https://www.selenium.dev/blog/2021/announcing-selenium-4/)

**Comment by vania-pooh** [comment] 2021-10-14 17:21
@doctor-house we know but this is not a standard capability and we have our own plans concerning client-side part of the WebDriver protocol. So I don't think we will follow this way because it is implementation-specific and we tend to be more independent from the main Selenium repository.

**Comment by Dor-bl** [comment] 2021-10-15 20:23
@doctor-house I would love to get some more information on the way you got this to work, before I put more time and effort into it.

**Comment by doctor-house** [comment] 2021-10-18 21:07
@Dor-bl I made a gist [here](https://gist.github.com/doctor-house/11f196b8fb8c171f54bb1cf4b968fab8) showing the basic steps, just note this relies on internal implementation details about the Selenium client so it may break in the future without warning.

**Comment by matthewlowry** [comment] 2021-11-09 04:49
I'm experiencing the same issue with the Selenium 4 Java client.

For the record, I tried the same work-around (reflectively inject the `se:cdp` and `se:cdpVersion` keys in the driver's capabilities) as suggested by @doctor-house and it worked. Gist for Java [here](https://gist.github.com/matthewlowry/69cc0c96e452d667b66adab4abd91db3).

It would be nice if Selenoid supported using the Selenium 4 CDP client.

**Comment by vania-pooh** [comment] 2021-11-09 07:59
@matthewlowry I don't think we'll support their approach as it is not standardized. Btw, instead we are creating our own version of Selenium Java client here: https://github.com/aerokube/lightning-java

**Comment by matthewlowry** [comment] 2021-11-11 00:18
@vania-pooh thanks for the reply I can appreciate you position. I've had a quick glance at that repo and I like the idea of a Java client with a much cleaner interface. The Selenium Java client has a lot of baggage.

**Comment by vania-pooh** [comment] 2022-06-22 08:01
Duplicate of #1063.

**Closed by vania-pooh** 2022-06-22 08:01 UTC
Labels: new-feature
