### ISSUE TITLE
Selenoid created new session before stop MicrosoftWebDriver for Edge browser on Windows

### ISSUE THREAD

**Issue by mdolinin** [aerokube/selenoid#223] opened 2017-09-20 13:25 UTC
Steps to reproduce:
1. Start selenoid on Windows with `-limit 1 -disable-docker` parameters
2. Run two tests that use MicrosoftEdge browser in parallel

Actual result:
Second test will fail with `500 internal error` from MicrosoftWebDriver

Expected result:
Second test continue running as first one

Details:
In selenoid output we can see that new session is started before MicrosoftWebDriver is stoped by selenoid.
For now Microsoft Edge doesn't support to run multiple sessions simultaneously 
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7186486/

Workaround:
1. Create separate batch file with timeout before starting new MicrosoftWebDriver process
2. In `browsers.json` set to run your batch file instead of MicrosoftWebDriver directly

**Comment by vania-pooh** [comment] 2017-09-20 14:13
Using batch files can lead to memory leak because Windows has no way to destroy the entire process tree with all child subprocesses.

**Comment by mdolinin** [comment] 2017-09-20 14:21
Agree. I forgot to write that you need to kill previous MicrosoftWebDriver process in batch file.

**Comment by vania-pooh** [comment] 2017-09-20 14:37
@mdolinin so you are saying that we can't start 2+ processes of EdgeDriver in parallel?

**Comment by mdolinin** [comment] 2017-09-20 14:43
Yes. You can start few EdgeDriver processes, but when you try to use them they will response with `500 internal error`

**Comment by vania-pooh** [comment] 2017-09-21 06:50
Ok, let me test this first. If Edge does not support this - the only thing we can do is to wait for this feature to be implemented.

**Comment by vania-pooh** [comment] 2017-10-05 16:37
I investigated the situation a bit more and can confirm that this is an Edge internal limitation which should be fixed in subsequent releases. I think this could be because of the hard-coded debug port  used for communication or essentially single-threaded debugger implementation. Anyway let's wait for the next Edge update to see whether they have fixed the issue.

**Comment by vania-pooh** [comment] 2017-10-19 14:08
Still reproduces with Edge `16.16299` and latest EdgeDriver.

**Closed** 2024-12-17 11:57 UTC
Labels: bug
