### ISSUE TITLE
Require image for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [aerokube/selenoid#1107] opened 2021-05-25 06:10 UTC
Hi Team,

I am trying to use the **selenoid/vnc** image on the arm64 platform but it seems it is not available for arm64.

I have successfully built the image using the command **docker build -t <image_name> .** on the arm64 platform by making some changes in the files **.github/workflows/build.yml** and **ci/build.sh**.

I have used Github actions to build and push the image for both the platforms.

**Commit Link -** https://github.com/odidev/selenoid/commit/67c0292a00446660dd6d09d0c7c7024438085b10

**Github actions link -** https://github.com/odidev/selenoid/runs/2662087679?check_suite_focus=true

**Docker Hub Link -** https://hub.docker.com/repository/registry-1.docker.io/odidev/selenoid/tags?page=1&ordering=last_updated

Do you have any plans on releasing arm64 images?

It will be very helpful if an arm64 image is available. If interested, I will raise a PR.

**Comment by vania-pooh** [comment] 2021-05-25 11:06
@odidev the problem is not building Selenoid for ARM - but rebuilding all browser images for ARM. :)

**Comment by odidev** [comment] 2021-05-27 11:57
@vania-pooh
As you have mentioned in the above comment that there is a problem in rebuilding all browser images for arm64 and I have checked in [dockerhub](https://hub.docker.com/r/selenoid/vnc/tags?page=1&ordering=last_updated) that there are different tags for selenoid/vnc image like firefox, opera and chrome but only one dockerfile is available in this repository. 

After digging more on this, I have got another [link](https://github.com/aerokube/images) where dockerfiles for [firefox](https://github.com/aerokube/images/blob/master/static/firefox/selenoid/Dockerfile), [opera](https://github.com/aerokube/images/blob/master/static/opera/Dockerfile) and [chrome](https://github.com/aerokube/images/blob/master/static/chrome/Dockerfile) is present but in these dockerfiles they are using different images like selenoid/dev_firefox, selenoid/dev_oper and selenoid/dev_chrome as base image which is only available for amd64 and I could not find source for these as well. I can help in building/uploading these images if you can provide the steps/source code for all these tags of selenoid/vnc image.

**Comment by vania-pooh** [comment] 2021-05-27 14:11
@odidev https://aerokube.com/images/latest/#_building_images Base layer source is here: https://github.com/aerokube/images/tree/master/selenium/base

**Comment by Pavel077** [comment] 2021-06-17 13:32
Hello.

@odidev were you able to build browser images for arm64?

**Comment by odidev** [comment] 2021-07-19 12:46
I have successfully built the [base image](https://github.com/aerokube/images/blob/master/selenium/base/Dockerfile)  using the command **docker build -t <image_name> .** on the arm64 platform by making some changes in **selenium/base/Dockerfile** file and used the manually build **browsers/base** image. I have successfully built the browser images of **chrome** and **Firefox** on arm64 as well.  

Please refer [here ](https://github.com/odidev/images/commit/7b671c2782a10c6333f429148d35e745a9582f9c) for the changes done to build base image and browser images. 

To build the opera image for arm64 opera-stable binary is required for arm64 but it is not available in the [official release](https://pkgs.org/download/opera-stable)  and it looks like source code for opera is private. 

If we can make browser images available, I will raise PR with these changes.

**Comment by rubyangxg** [comment] 2021-09-24 08:46
@odidev  can you push your arm image to docker hub

**Comment by odidev** [comment] 2022-01-12 10:44
@rubyangxg I have pushed arm64 images of both chrome and Firefox to my dockerhub account. 

**Chrome image link:** https://hub.docker.com/repository/docker/odidev/chrome_arm64 

**Firefox image link:** https://hub.docker.com/repository/docker/odidev/firefox_arm64

**Comment by gromanas** [comment] 2022-02-12 17:09
@odidev Could you please provide some more context on how to use those custom images with selenoid? Thank you in advance

**Comment by gromanas** [comment] 2022-02-12 18:16
@odidev I pulled your images and I tried to start a container of one of each, but I am not able, as they keep failing. The command I used is `docker run odidev/chrome_arm64:latest`.

**Comment by odidev** [comment] 2022-02-15 06:41
@gromanas I pulled both the images and tried to start a container for both and container is starting successfully for both the image using command docker run -it image_name . Please see the log below for both the images. 

  

**For Chrome:** 

``` 

odidev@ubuntuarm:~/FAAS_Project$ docker pull odidev/chrome_arm64:latest 

latest: Pulling from odidev/chrome_arm64 

Digest: sha256:4c6a4ae2ce1a2fb0e914adea35670fc979b8a87e38ea39bc904175de9cadb3e5 

Status: Image is up to date for odidev/chrome_arm64:latest 

docker.io/odidev/chrome_arm64:latest 

odidev@ubuntuarm:~/FAAS_Project$ docker run -it odidev/chrome_arm64:latest 

root@67c8a836ad3e:/# uname -a 

Linux 67c8a836ad3e 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:31:47 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux 

root@67c8a836ad3e:/# 

``` 

 

**For Firefox:**  

```  

odidev@ubuntuarm:~/FAAS_Project$ docker pull odidev/firefox_arm64:latest 

latest: Pulling from odidev/firefox_arm64 

Digest: sha256:68a51fa282925b17a66f444325d82ac228f48c3028937ca39c51249e7e6a271f 

Status: Image is up to date for odidev/firefox_arm64:latest 

docker.io/odidev/firefox_arm64:latest 

odidev@ubuntuarm:~/FAAS_Project$ docker run -it odidev/firefox_arm64:latest 

root@d929fa0aa24b:/# uname -a 

Linux d929fa0aa24b 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:31:47 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux 

```

**Comment by sskorol** [comment] 2022-05-01 21:17
@odidev have you even tried to run your images with Selenoid? If you've built them the way you described -> directly via Dockerfile, it won't work out of the box. Selenoid team uses a go-driven process which assumes building not just a raw browser image, but also attaching a driver to it + a special [entrypoint](https://github.com/aerokube/images/blob/master/static/chrome/entrypoint.sh). Moreover, your changes in Dockerfile for Chromium are based on Ubuntu 20.04, which has a set of known issues that prevent you from installing Chromium directly w/o dpkg. On the other hand, if you take a look at the official packages for Ubuntu Focal, there's only an [ancient](https://packages.ubuntu.com/focal/chromium-browser) Chromium version available. They don't ship new versions for Focal. So you should either fetch Chromium from 18.04 or 21.

P.S. I've also bashed to your chrome image and there's actually no chromium or chrome installed. I really appreciate your work. But how did you test your images besides checking OS info?

**Comment by sskorol** [comment] 2022-05-03 18:03
FYI, created a draft PR https://github.com/aerokube/images/pull/524 with a build script. Or you can test it with a [prebuilt image](https://hub.docker.com/r/sskorol/selenoid_chromium_vnc/tags).

**Comment by odidev** [comment] 2022-05-04 09:13
@ sskorol  

  

As chrome is not available for arm64 so I have installed chromium-browser in the [Dockerfile](https://github.com/odidev/images/commit/7b671c2782a10c6333f429148d35e745a9582f9c#diff-64f86530c09922b7d5998a32f410202dd69b964ab46b0e1eaf43cc271d7254d4R15) through apt-get and released the arm64 image for chrome in my [dockerhub](https://hub.docker.com/repository/docker/odidev/chrome_arm64), However I have not tested my arm64 chrome browser images with Selenoid. 

 

Anyway thanks for the [PR](https://github.com/aerokube/images/pull/524) with a build script and prebuilt [chromium](https://hub.docker.com/r/sskorol/selenoid_chromium_vnc/tags) arm64 image which will help to test images with Selenoid.

**Comment by sskorol** [comment] 2022-05-04 09:42
@odidev but as I've mentioned above, a [base image](https://github.com/odidev/images/commit/7b671c2782a10c6333f429148d35e745a9582f9c#diff-76add6ffc78c78fbfd0e21a5cd113e896d54df9b291232cac45acc80339425b8L18) uses `ubuntu:20.04` which doesn't ship new [Chromium](https://packages.ubuntu.com/search?keywords=chromium) updates. Also, you can't install Chromium correctly on `ubuntu:20.04` w/o snap. Here's a proof:

```Dockerfile
FROM ubuntu:20.04

RUN apt-get update && apt-get install -y chromium-browser

CMD ["chromium-browser", "--version"]
```

Then run it:
```bash
❯ docker run -it [your_image_name]

Command '/usr/bin/chromium-browser' requires the chromium snap to be installed.
Please install it with:

snap install chromium
```

So the image you've built doesn't have either working Chromium or chromium-driver, unfortunately. However, when you change the base to `ubuntu:18.04`, it becomes a gamechanger.

**Comment by odidev** [comment] 2022-05-04 11:31
@ sskorol 

  

I have verified the chrome image which I have build for arm64 doesn't have working Chromium. Thanks for your suggestions and workaround.

**Comment by vania-pooh** [comment] 2022-06-25 14:58
Seems to be fixed in #1237.

**Closed by vania-pooh** 2022-06-25 14:58 UTC
Labels: new-feature

**Comment by gromanas** [comment] 2022-07-04 13:28
Thank you very much! Are there any official arm64 images?

**Comment by gromanas** [comment] 2022-07-04 16:34
Thank you very much for the quick response and the update!!!

**Comment by gromanas** [comment] 2022-10-10 12:37
@vania-pooh Hello! I would like to ask if we have any updates concerning the arm64 browser images. Thank you in advance!

**Comment by vania-pooh** [comment] 2022-10-10 13:51
This one was released in https://github.com/aerokube/selenoid/releases/tag/1.10.8. However browser images are still not ready.

**Comment by gromanas** [comment] 2022-10-17 08:40
@vania-pooh Thank you very much! Do you have any plans to support arm64 browser images? Any instructions on how to create our own? I have several issues following the official instrunctions. Thank you again in advance!

**Comment by vania-pooh** [comment] 2022-10-17 09:27
@gromanas probably, but no estimate exists.

**Comment by aandryashin** [comment] 2022-11-09 10:16
Hello! Please try this:

https://github.com/aandryashin/moon-on-apple-silicon

ср, 9 нояб. 2022 г., 13:05 Yiorgis Gozadinos ***@***.***>:

**Comment by ggozad** [comment] 2022-11-09 10:42
> Hello! Please try this: https://github.com/aandryashin/moon-on-apple-silicon ср, 9 нояб. 2022 г., 13:05 Yiorgis Gozadinos ***@***.***>:
> […](#)

Thanks!

Here's what I tried:
`browsers.json`
```
{
  "firefox": {
    "default": "latest",
    "versions": {
      "latest": {
        "image": "quay.io/browser/firefox:100.0.0-0",
        "port": "4444",
        "path": "/wd/hub",
        "tmpfs": { "/tmp": "size=512m" }
      }
    }
  },
  "chrome": {
    "default": "latest",
    "versions": {
      "latest": {
        "image": "quay.io/browser/chromium:100.0.4896.127-0",
        "port": "4444",
        "tmpfs": { "/tmp": "size=512m" }
      }
    }
  }
}
```

But then I see for both 
```
behaving-selenoid-1  | 2022/11/09 10:29:38 [-] [NEW_REQUEST] [unknown] [192.168.96.4]
behaving-selenoid-1  | 2022/11/09 10:29:38 [-] [NEW_REQUEST_ACCEPTED] [unknown] [192.168.96.4]
behaving-selenoid-1  | 2022/11/09 10:29:38 [0] [LOCATING_SERVICE] [chrome] []
behaving-selenoid-1  | 2022/11/09 10:29:38 [-] [DEFAULT_VERSION] [Using default version: latest]
behaving-selenoid-1  | 2022/11/09 10:29:38 [0] [USING_DOCKER] [chrome] [latest]
behaving-selenoid-1  | 2022/11/09 10:29:38 [0] [CREATING_CONTAINER] [quay.io/browser/chromium:100.0.4896.127-0]
behaving-selenoid-1  | 2022/11/09 10:29:38 [0] [STARTING_CONTAINER] [quay.io/browser/chromium:100.0.4896.127-0] [cd3a81190d3c651ae6109749500efeb6ddbecb0a5c5ac62a37d71862ae1ff62f]
behaving-selenoid-1  | 2022/11/09 10:29:38 [0] [CONTAINER_STARTED] [quay.io/browser/chromium:100.0.4896.127-0] [cd3a81190d3c651ae6109749500efeb6ddbecb0a5c5ac62a37d71862ae1ff62f] [0.30s]
behaving-selenoid-1  | 2022/11/09 10:30:08 [0] [REMOVING_CONTAINER] [cd3a81190d3c651ae6109749500efeb6ddbecb0a5c5ac62a37d71862ae1ff62f]
behaving-selenoid-1  | 2022/11/09 10:30:09 [0] [CONTAINER_REMOVED] [cd3a81190d3c651ae6109749500efeb6ddbecb0a5c5ac62a37d71862ae1ff62f]
behaving-selenoid-1  | 2022/11/09 10:30:09 [0] [SERVICE_STARTUP_FAILED] [wait: http://192.168.96.5:4444 does not respond in 30s]
```

**Comment by aandryashin** [comment] 2022-11-09 11:58
Arm64 images are working only with moon.

ср, 9 нояб. 2022 г., 13:42 Yiorgis Gozadinos ***@***.***>:

**Comment by ggozad** [comment] 2022-11-09 13:17
> Our further plan is to rewrite selenoid to use the same images that moon uses, then provide arm64 images for both moon and new selenoid. ср, 9 нояб. 2022 г., 15:27 Yiorgis Gozadinos ***@***.***>:

I see, thank you @aandryashin for the insight!

**Comment by Haarolean** [comment] 2023-04-03 06:50
@aandryashin shouldn't this be reopened until there are images?

**Comment by aandryashin** [comment] 2023-04-03 08:14
We are not planning to provide and support arm64 images for selenoid, you
can build then yourself if needed.

пн, 3 апр. 2023 г., 09:50 Roman Zabaluev ***@***.***>:

**Comment by nickmsix** [comment] 2024-04-02 12:29
@gromanas did you manage to find the solution for getting/generation the arm64 chrome/chromium images?

**Comment by nickmsix** [comment] 2024-04-02 13:26
@gromanas Greate job!!! 👍
Please share detailed steps on how to make such images 🙏
