### ISSUE TITLE
Selenoid UI goes down intermittently on SLES 15 SP4 VM but container stays up and no discrepancy found in logs.

### ISSUE THREAD

**Issue by iamgopalan** [aerokube/selenoid#1419] opened 2024-04-23 09:16 UTC
Everything is working fine and suddenly the selenoid url will stop working and when I inspected network from browser console I see failed to load response data: no resource with given identifier found issue but if I log inside VM and check docker o/p everything looks good.

The only way for me to resolve this issue is I need to reboot VM and once VM is back online I can see that selenoid UI is working fine ?

How to debug this kind of issue further as selenoid logs does not capture any discrepancies or root cause of this intermittent issue ?

We never know what users can do or do not have any control on what actions they do on selenoid UI which is causing this intermittent issue. Please advise how this can be root caused ?

Attached logs for detailed debugging and analysis.
[selenoidcorelogs.txt](https://github.com/aerokube/selenoid/files/15074329/selenoidcorelogs.txt)

[selenoiduilogs.txt](https://github.com/aerokube/selenoid/files/15074334/selenoiduilogs.txt)

docker ps -a
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
bc4f1cf1c82f selenoid/video-recorder:latest-release "/entrypoint.sh" 2 minutes ago Up 2 minutes practical_rubin
0e956df58a19 selenoid/vnc_chrome:120.0 "/entrypoint.sh" 2 minutes ago Up 2 minutes 4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp focused_neumann
00a10bd67c08 aerokube/selenoid-ui "/selenoid-ui --sele…" 3 months ago Up 43 minutes (healthy) 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp docker_selenoid-ui_1
e7ae0f8eace7 aerokube/selenoid "/usr/bin/selenoid -…" 3 months ago Up 43 minutes 0.0.0.0:4444->4444/tcp, :::4444->4444/tcp docker_selenoid_1

uname -r
5.14.21-150400.24.111-default

cat /etc/os-release
NAME="SLES"
VERSION="15-SP4"
VERSION_ID="15.4"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp4"
DOCUMENTATION_URL="https://documentation.suse.com/"

**Comment by iamgopalan** [comment] 2024-04-23 09:23
How do i differentiate whether its a OS level issue or selenoid container issue and why OS level problem causes intermittent issues for selenoid and how to prove this using logs and rectify same permanently ?

**Comment by vania-pooh** [comment] 2024-04-30 05:20
Duplicate of https://github.com/aerokube/selenoid-ui/issues/537.

**Closed by vania-pooh** 2024-04-30 05:20 UTC
