### ISSUE TITLE
Selenoid not recording video on Win10 Pro

### ISSUE THREAD

**Issue by Varro88** [aerokube/selenoid#1017] opened 2020-11-06 08:57 UTC
Hi! Could you please help - on Windows 10 I'm not able to record/save videos. VNC is enabled, I can see test running in selenoid-ui, but folder video directory is always empty, http://localhost:4444/video/ displays blank page, http://localhost:4444/video/selenoid%sessionId%.mp4 returns 404.
The same project (with appropriate changes to pathes) is working and saving videos on Linux Mint.

I run via `docker-compose up` following yaml:

```
version: '3.4'

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: "selenoid"
    volumes:
      - "/p/QA/SelenoidTest/selenoid:/etc/selenoid"
      - "/p/QA/SelenoidTest/selenoid/video:/opt/selenoid/video"
      - "/p/QA/SelenoidTest/selenoid/logs:/opt/selenoid/logs"
      - "/p/QA/SelenoidTest/selenoid/downloads:/home/selenium/Downloads"
      - "//var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/p/QA/SelenoidTest/selenoid/video/
    command: ["-capture-driver-logs", "-save-all-logs", "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-timeout", "10m", "-capture-driver-logs"]
    ports:
      - "4444:4444"
    network_mode: bridge
  selenoid-ui:
    image: aerokube/selenoid-ui
    container_name: "selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri","http://selenoid:4444" ]
```

And here's full log:

```
P:\QA\SelenoidTest> docker-compose up
Starting selenoid ... done
Starting selenoid-ui ... done
Attaching to selenoid, selenoid-ui
selenoid       | 2020/11/06 08:21:11 [-] [INIT] [Loading configuration files...]
selenoid       | 2020/11/06 08:21:11 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
selenoid       | 2020/11/06 08:21:11 [-] [INIT] [Video Dir: /opt/selenoid/video]
selenoid       | 2020/11/06 08:21:11 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
selenoid       | 2020/11/06 08:21:11 [-] [INIT] [Saving all logs]
selenoid       | 2020/11/06 08:21:11 [-] [INIT] [Your Docker API version is 1.40]
selenoid       | 2020/11/06 08:21:11 [-] [INIT] [Timezone: UTC]
selenoid       | 2020/11/06 08:21:11 [-] [INIT] [Listening on :4444]
selenoid-ui    | 2020/11/06 08:21:11 [INIT] [Listening on :8080]
selenoid       | 2020/11/06 08:21:22 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
selenoid       | 2020/11/06 08:21:22 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
selenoid       | 2020/11/06 08:21:22 [0] [LOCATING_SERVICE] [chrome] [86.0]
selenoid       | 2020/11/06 08:21:22 [0] [USING_DOCKER] [chrome] [86.0]
selenoid       | 2020/11/06 08:21:22 [0] [CREATING_CONTAINER] [selenoid/vnc:chrome_86.0]
selenoid       | 2020/11/06 08:21:22 [0] [STARTING_CONTAINER] [selenoid/vnc:chrome_86.0] [2ae25f0b731510cbbe78468c855624a0d1f104ee521c0a256d5166957478de41]
selenoid       | 2020/11/06 08:21:22 [0] [CONTAINER_STARTED] [selenoid/vnc:chrome_86.0] [2ae25f0b731510cbbe78468c855624a0d1f104ee521c0a256d5166957478de41] [0.21s]
selenoid       | 2020/11/06 08:21:22 [0] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
selenoid       | 2020/11/06 08:21:22 [0] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [5cfa721a87614988efb933adf64f231626e95224c7842f1bc18b8b44dae4ccd8]
selenoid       | 2020/11/06 08:21:22 [0] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [5cfa721a87614988efb933adf64f231626e95224c7842f1bc18b8b44dae4ccd8] [0.24s]
selenoid       | 2020/11/06 08:21:22 [0] [SERVICE_STARTED] [selenoid/vnc:chrome_86.0] [2ae25f0b731510cbbe78468c855624a0d1f104ee521c0a256d5166957478de41] [0.10s]
selenoid       | 2020/11/06 08:21:22 [0] [PROXY_TO] [2ae25f0b731510cbbe78468c855624a0d1f104ee521c0a256d5166957478de41] [http://172.17.0.4:4444]
selenoid       | 2020/11/06 08:21:22 [0] [SESSION_ATTEMPTED] [http://172.17.0.4:4444] [1]
selenoid       | 2020/11/06 08:21:22 [0] [SESSION_CREATED] [cd71e146d3b3ef376bb3f1403647ec9f] [1] [0.84s]
selenoid       | 2020/11/06 08:21:33 [30] [SESSION_DELETED] [cd71e146d3b3ef376bb3f1403647ec9f]
selenoid       | 2020/11/06 08:21:33 [0] [STOPPING_VIDEO_CONTAINER] [5cfa721a87614988efb933adf64f231626e95224c7842f1bc18b8b44dae4ccd8]
selenoid       | 2020/11/06 08:21:34 [0] [REMOVING_CONTAINER] [5cfa721a87614988efb933adf64f231626e95224c7842f1bc18b8b44dae4ccd8]
selenoid       | 2020/11/06 08:21:34 [0] [FAILED_TO_REMOVE_CONTAINER] [5cfa721a87614988efb933adf64f231626e95224c7842f1bc18b8b44dae4ccd8] [Error response from daemon: removal of container 5cfa721a87614988efb933adf64f231626e95224c7842f1bc18b8b44dae4ccd8 is already in progress]
selenoid       | 2020/11/06 08:21:34 [0] [REMOVING_CONTAINER] [2ae25f0b731510cbbe78468c855624a0d1f104ee521c0a256d5166957478de41]
selenoid       | 2020/11/06 08:21:34 [0] [CONTAINER_REMOVED] [2ae25f0b731510cbbe78468c855624a0d1f104ee521c0a256d5166957478de41]
selenoid       | 2020/11/06 08:21:34 [0] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoid7b08eee3d902d5a9ee0f1360b49bb510.mp4 to /opt/selenoid/video/cd71e146d3b3ef376bb3f1403647ec9f.mp4: rename /opt/selenoid/video/selenoid7b08eee3d902d5a9ee0f1360b49bb510.mp4 /opt/selenoid/video/cd71e146d3b3ef376bb3f1403647ec9f.mp4: no such file or directory]
```

**Comment by vania-pooh** [comment] 2020-11-06 14:12
@Varro88 for some reason video recorder container does not even start (removed before video is copied):
```
selenoid       | 2020/11/06 08:21:34 [0] [REMOVING_CONTAINER] [5cfa721a87614988efb933adf64f231626e95224c7842f1bc18b8b44dae4ccd8]
selenoid       | 2020/11/06 08:21:34 [0] [FAILED_TO_REMOVE_CONTAINER] [5cfa721a87614988efb933adf64f231626e95224c7842f1bc18b8b44dae4ccd8] [Error response from daemon: removal of container 5cfa721a87614988efb933adf64f231626e95224c7842f1bc18b8b44dae4ccd8 is already in progress]
```
Did you enable sharing respective disk in Docker settings?

**Comment by Varro88** [comment] 2020-11-06 14:50
@vania-pooh I use WSL2 mode and as far as I understand (according to "FILE SHARING" section on https://docs.docker.com/docker-for-windows/ ) directory sharing is enabled by default:

> The File sharing tab is only available in Hyper-V mode, because in WSL 2 mode and Windows container mode all files are automatically shared by Windows.

And I have write acess to local files from other containers like

```
C:\Users\User> docker run -it -v p:/docker:/docker alpine sh
/ # cd docker && touch testfile1 
```

**Comment by vania-pooh** [comment] 2020-11-08 14:23
@Varro88 Selenoid starts video container as follows:

```bash
$ docker run --name selenium -d selenoid/chrome:85.0
$ docker run --rm -v /p/QA/SelenoidTest/selenoid/video:/data  --link selenium -e FILE_NAME=/data/video.mp4 selenoid/video-recorder:latest-release
```

Please try to start these two containers and take a look at video recorder logs.

**Comment by Varro88** [comment] 2020-11-09 18:57
Hi @vania-pooh 

> $ docker run --name selenium -d selenoid/chrome:85.0

Container is running and port 4444 seems to be listened
```
$ ss -tulw
Netid       State         Recv-Q        Send-Q                Local Address:Port               Peer Address:Port        
tcp         LISTEN        0             128                         0.0.0.0:6099                    0.0.0.0:*           
tcp         LISTEN        0             5                                 *:4444                          *:*           
tcp         LISTEN        0             128                               *:7070                          *:*           
tcp         LISTEN        0             128                               *:9090                          *:*           
tcp         LISTEN        0             128                               *:8080                          *:*           
tcp         LISTEN        0             128                            [::]:6099                       [::]:*                
```

But when tried to run tests I've got `org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.` http://127.0.0.1:4444/stats is also inaccessible

> $ docker run --rm -v /p/QA/SelenoidTest/selenoid/video:/data  --link selenium -e FILE_NAME=/data/video.mp4 selenoid/video-recorder:latest-release

After this I've got endless "Sleeping before next attempt..."
```
Waiting for display to open...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
```

**Comment by vania-pooh** [comment] 2020-11-10 03:52
@Varro88 video recorder tries to connect to port 6099 (X-server port) of browser container. Need to check whether video recorder has access to this port.

**Comment by Varro88** [comment] 2020-11-10 08:37
@vania-pooh sorry, could you please clarify how can I check it? Because when I'm running from inside video-recorder container
`/ # nc -zv 127.0.0.1 6099`
It just returns nothing.

**Comment by vania-pooh** [comment] 2020-11-10 09:59
@Varro88 I would do:
```
# nc -vz selenoid 6099
```

**Comment by Varro88** [comment] 2020-11-10 12:43
@vania-pooh it seems port is accessible:
```
/ # nc -vz selenium 6099
selenium (172.17.0.2:6099) open
```

**Comment by vania-pooh** [comment] 2020-11-10 13:52
@Varro88 this is where log messages are being produced. https://github.com/aerokube/images/blob/master/selenium/video/entrypoint.sh#L20-L29 You could try to reproduce yourself in terminal.

**Comment by hristo831** [comment] 2020-12-21 11:30
Hi,
I have the same issue.
I have .Net project and run tests inside Docker on Windows 10.
I start Selenoid via Configuration Manager.
**Copy of my C# code:**
`        public void SetupTest()
        {
            var driverOptions = new ChromeOptions();

            var runName = GetType().Assembly.GetName().Name;
            var timestamp = $"{DateTime.Now:yyyyMMdd.HHmm}";

            driverOptions.BrowserVersion = "87.0";
            driverOptions.AddAdditionalCapability("name", runName, true);
            driverOptions.AddAdditionalCapability("videoName", $"{runName}.{timestamp}.mp4", true);
            driverOptions.AddAdditionalCapability("logName", $"{runName}.{timestamp}.log", true);
            driverOptions.AddAdditionalCapability("enableVNC", true, true);
            driverOptions.AddAdditionalCapability("enableVideo", true, true);
            driverOptions.AddAdditionalCapability("enableLog", true, true);
            driverOptions.AddAdditionalCapability("screenResolution", "1920x1080x24", true);

            driverOptions.AddArgument("--start-maximized");
            driverOptions.AddArgument("--incognito");

            _driver = new RemoteWebDriver(new Uri("http://127.0.0.1:4444/wd/hub"), driverOptions);
            _driver.Manage().Timeouts().PageLoad = TimeSpan.FromSeconds(60);
        }`

**Screenshot of running containers**
![22 05 1](https://user-images.githubusercontent.com/29305280/102772189-c3d78d80-438f-11eb-8f1d-603b5e7c161d.png)

**Screenshot of Selenoid status**
![21 12 2](https://user-images.githubusercontent.com/29305280/102772416-1e70e980-4390-11eb-864d-69b131786d3d.png)

**Screenshot of Powershell**
![21 12 3](https://user-images.githubusercontent.com/29305280/102772592-74de2800-4390-11eb-888f-3cb52b035dc3.png)

When the test finish there are no file http://127.0.0.1:4444/videos.

Is there any update on this issue?

**Comment by vania-pooh** [comment] 2020-12-22 14:52
@hristo831 there should be an error message in Selenoid container logs with `VIDEO_ERROR` status then.

**Comment by hristo831** [comment] 2020-12-24 06:32
@vania-pooh you were right there is an error in the logs.
![23 12 1](https://user-images.githubusercontent.com/29305280/103066716-1d270300-45c2-11eb-8bd5-1bb80035139b.png)

I figured out where my configuration error was.
Тhanks for the help!!!

**Comment by vania-pooh** [comment] 2020-12-24 16:45
Closing then.

**Closed by vania-pooh** 2020-12-24 16:45 UTC

**Comment by VickoValch** [comment] 2021-01-07 12:53
@hristo831 I'm having the exact same issue as you described, do you mind sharing your solution here?

**Comment by vania-pooh** [comment] 2021-01-07 17:54
@VickoValch you have to set OVERRIDE_VIDEO_OUTPUT_DIR to correct value.

**Comment by VickoValch** [comment] 2021-01-08 07:16
@vania-pooh I thought this wont be required when starting selenoid through the config. manager. I use the following command to do so: 
`cm selenoid start --vnc --browsers chrome `
on a Windows 10 Pro env. this seems to be successful in returning the log to the selenoid folder, but the video is never successfully renamed due to the same error @hristo831 described. I don't think OVERRIDE_VIDEO_OUTPUT_DIR can be set as argument when using CM, should I head down the docker compose way?

**Comment by vania-pooh** [comment] 2021-01-08 18:24
@VickoValch could you please show `docker inspect selenoid` output when starting everything with cm tool?

**Comment by VickoValch** [comment] 2021-01-09 07:42
@vania-pooh sure, here it is:
```
[
    {
        "Id": "a1e20f1c635beb092c862557554b83263f0cab01f357a6fc6e76c7f988191d8e",
        "Created": "2021-01-09T07:34:24.4829932Z",
        "Path": "/usr/bin/selenoid",
        "Args": [
            "-listen",
            ":4444",
            "-conf",
            "/etc/selenoid/browsers.json",
            "-video-output-dir",
            "/opt/selenoid/video/",
            "-conf",
            "/etc/selenoid/browsers.json",
            "-video-output-dir",
            "/opt/selenoid/video/",
            "-video-recorder-image",
            "selenoid/video-recorder:latest-release",
            "-log-output-dir",
            "/opt/selenoid/logs/",
            "-container-network",
            "selenoid"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 898,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-01-09T07:34:24.7980456Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:c349d7b3e7e421496b2f2867c1d4306d79f221ebfdd75539e7b93fa02d4272fd",
        "ResolvConfPath": "/var/lib/docker/containers/a1e20f1c635beb092c862557554b83263f0cab01f357a6fc6e76c7f988191d8e/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/a1e20f1c635beb092c862557554b83263f0cab01f357a6fc6e76c7f988191d8e/hostname",
        "HostsPath": "/var/lib/docker/containers/a1e20f1c635beb092c862557554b83263f0cab01f357a6fc6e76c7f988191d8e/hosts",
        "LogPath": "/var/lib/docker/containers/a1e20f1c635beb092c862557554b83263f0cab01f357a6fc6e76c7f988191d8e/a1e20f1c635beb092c862557554b83263f0cab01f357a6fc6e76c7f988191d8e-json.log",
        "Name": "/selenoid",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/c/Users/viktor.valchev/.aerokube/selenoid:/etc/selenoid:ro,Z",
                "/c/Users/viktor.valchev/.aerokube/selenoid/video:/opt/selenoid/video:Z",
                "/c/Users/viktor.valchev/.aerokube/selenoid/logs:/opt/selenoid/logs:Z",
                "//var/run/docker.sock:/var/run/docker.sock"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "selenoid",
            "PortBindings": {
                "4444/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "4444"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/b3c63406b50a4918b4a029d5d1b66b7965260c2424a441a307aa3821144b6d94-init/diff:/var/lib/docker/overlay2/a47afebe02dbf2a984958fdc07a592191e0cb345c52e57b440740e5f3c6c91f9/diff:/var/lib/docker/overlay2/63915748826bfe3d051195537511969bb3795eb821337d6edfa48b4f3e7bda66/diff:/var/lib/docker/overlay2/d1419bff8f9b62aa5b54c61ce6c59f8a43f6b830b30a2d50a4ce60cad5e066fc/diff",
                "MergedDir": "/var/lib/docker/overlay2/b3c63406b50a4918b4a029d5d1b66b7965260c2424a441a307aa3821144b6d94/merged",
                "UpperDir": "/var/lib/docker/overlay2/b3c63406b50a4918b4a029d5d1b66b7965260c2424a441a307aa3821144b6d94/diff",
                "WorkDir": "/var/lib/docker/overlay2/b3c63406b50a4918b4a029d5d1b66b7965260c2424a441a307aa3821144b6d94/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/c/Users/viktor.valchev/.aerokube/selenoid",
                "Destination": "/etc/selenoid",
                "Mode": "ro,Z",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/c/Users/viktor.valchev/.aerokube/selenoid/video",
                "Destination": "/opt/selenoid/video",
                "Mode": "Z",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/c/Users/viktor.valchev/.aerokube/selenoid/logs",
                "Destination": "/opt/selenoid/logs",
                "Mode": "Z",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "//var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "localhost",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "4444/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "OVERRIDE_VIDEO_OUTPUT_DIR=/c/Users/viktor.valchev/.aerokube/selenoid/video",
                "DOCKER_API_VERSION=1.41",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "-conf",
                "/etc/selenoid/browsers.json",
                "-video-output-dir",
                "/opt/selenoid/video/",
                "-video-recorder-image",
                "selenoid/video-recorder:latest-release",
                "-log-output-dir",
                "/opt/selenoid/logs/",
                "-container-network",
                "selenoid"
            ],
            "Image": "aerokube/selenoid:1.10.0",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/usr/bin/selenoid",
                "-listen",
                ":4444",
                "-conf",
                "/etc/selenoid/browsers.json",
                "-video-output-dir",
                "/opt/selenoid/video/"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "baa5793c7d877c74869d4def3886a78ef9cc4260dd95bae4a6e1b6f236362e07",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "4444/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "4444"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/baa5793c7d87",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "selenoid": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "a1e20f1c635b",
                        "localhost"
                    ],
                    "NetworkID": "b1a605c391db6909f84e98f99db813c78eef2f043f158b138b207f697f4bf5f3",
                    "EndpointID": "097fa65c1b81d9d3135ffa60192188ecbc16c592bbe8b7d329f52d5e2c6f4a96",
                    "Gateway": "172.24.0.1",
                    "IPAddress": "172.24.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:18:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Comment by vania-pooh** [comment] 2021-01-09 12:39
@Varro88 Everything is configured correctly. For some reason your video container does not start. Try to remove all capabilities like videoName, videoCodec and so on and check whether it works.

**Comment by VickoValch** [comment] 2021-01-11 09:01
@vania-pooh Well actually it starts, I have no capabilities about videoName, videoCodec, etc. Here are my current capabilities:
```
    desiredCapabilities.setCapability("browserName", "chrome")
    desiredCapabilities.setCapability("browserVersion", "87.0")
    desiredCapabilities.setCapability("timeZone", "Europe/Berlin")
    desiredCapabilities.setCapability("enableLog", true)
    desiredCapabilities.setCapability("enableVideo", true)
    desiredCapabilities.setCapability("enableVNC", true)
```
Removing the enableLog will as expected not store any logs in the configured folder. That's what I see in the selenoid container log:
![image](https://user-images.githubusercontent.com/29303189/104161865-3b7f6200-53fc-11eb-8fa3-72154590e1b9.png)

Any ideas?

**Comment by vania-pooh** [comment] 2021-01-11 09:04
@VickoValch try to output video container logs with `docker logs`. This container should quickly appear and then remove.

**Comment by VickoValch** [comment] 2021-01-11 16:27
@vania-pooh Here's the log:
```
Waiting for display to open...
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.3.0 (Alpine 8.3.0)
  configuration: --prefix=/usr --enable-avfilter --enable-gpl --enable-libx264 --enable-static --enable-small --disable-ffplay --disable-ffprobe --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-w32threads --disable-alsa --disable-audiotoolbox --disable-cuda --disable-cuvid --disable-d3d11va --disable-dxva2 --disable-nvenc --disable-vaapi --disable-vdpau --disable-videotoolbox --disable-librtmp --disable-devices --enable-indev=xcbgrab --disable-debug
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[x11grab @ 0x56304099e100] Cannot get the image data event_error: response_type:0 error_code:128 sequence:9 resource_id:4194304 minor_code:4 major_code:130.
[x11grab @ 0x56304099e100] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, x11grab, from '172.24.0.3:99':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1080, 12 fps, 1000k tbr, 1000k tbn, 1000k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x7fcc411fb300] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7fcc411fb300] profile High, level 4.0
[libx264 @ 0x7fcc411fb300] 264 - core 152 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=12 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/data/selenoid265004a3545bb72fa227b1421580006a.mp4':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 1920x1080, q=-1--1, 12 fps, 12288 tbn, 12 tbc
    Metadata:
      encoder         : Lavc58.54.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
```

**Comment by vania-pooh** [comment] 2021-01-11 17:36
@VickoValch ffmpeg does not seem to save the video at the end. Check whether video container is killed because of OOM.

**Comment by VickoValch** [comment] 2021-01-12 16:57
@vania-pooh I'm not exactly sure how to trace if the container was killed because of OOM. Just a simple container stats shows me that the video recorder container uses max ~ 60 % cpu and 700 MB mem. and the browser container uses max ~ 300% cpu and 500 MB mem.
Should I try to pass some limiting parameters for the containers in the browsers.json as described in the documentation?

**Comment by vania-pooh** [comment] 2021-01-12 17:00
@VickoValch can check in `dmesg` output.

**Comment by VickoValch** [comment] 2021-01-13 16:27
@vania-pooh running `docker exec [video-recording container] dmesg` returns a `dmesg: klogctl: Operation not permitted` message, which I haven't been able to work around so far.

**Comment by vania-pooh** [comment] 2021-01-14 09:12
@VickoValch should run `dmesg` on the host machine (not inside container).

**Comment by VickoValch** [comment] 2021-01-18 16:43
@vania-pooh sorry but the host machine is a window 10 pro one, so the `dmesg` is not available. I wasn't able to find a good alternative command for window. In the mean time I also tried to increase the resources available to each container, but this didn't help as well.

**Comment by vania-pooh** [comment] 2021-01-19 04:00
@VickoValch On Windows Docker is still running under Linux being launched in a virtual machine (VirtualBox or Hyper-V). Make sure that you gave sufficient CPUs \ memory to this VM in Docker advanced settings.

**Comment by VickoValch** [comment] 2021-01-20 09:14
@vania-pooh Latest update - Even tho I increased the resources for each container still I was getting no progress. However after changing my docker to use the Hyper-V backend, sharing the .selenoid folder with the container in the Docker advanced settings and pulling the container images manully, it seems that the issue is now fixed. 
Is the WSL  2 docker backend somehow not working with selenoid?

**Comment by vania-pooh** [comment] 2021-01-20 10:18
@VickoValch at least not tested with this backend.

**Comment by VickoValch** [comment] 2021-01-20 13:53
@vania-pooh ok then I hope this discussion serves as example to others that encounter the same issue. Thanks for the support :)

**Comment by nakov** [comment] 2021-06-28 16:00
I has the same problem in Windows 10.
 - When I use the WSL2-based engine in Docker, the video recording fails.
 - When I switched to the Hyper-V-based engine in Docker, the video recording runs correctly.
Looks like this is a bug in Selenoid video recording infrastructure: it does not support WSL2.

**Comment by VinothMessi** [comment] 2021-07-14 13:35
Am using Windows 10 Pro machine:

**My Docker compose file:**
version: '3.8'
services:
  selenoid:
    image: aerokube/selenoid
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "/C/Passion/TestProject/opensdk/java-bot/config/:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/C/Passion/TestProject/opensdk/java-bot/config/video:/opt/selenoid/video"
      - "/C/Passion/TestProject/opensdk/java-bot/config/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/C/Passion/TestProject/opensdk/java-bot/config/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs" ]
  selenoid-ui:
    image: aerokube/selenoid-ui
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8090:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

**Using the below capabilities:**
DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("browserName", "chrome");
        capabilities.setCapability("browserVersion", selenoid.getVersion());
        capabilities.setCapability("enableVNC", true));
        capabilities.setCapability("enableVideo", true));
        capabilities.setCapability("videoName", "my-cool-video.mp4");
        capabilities.setCapability("enableLog", true));
        capabilities.setCapability("logName", "my-cool-log.log");

Am not able to see logs or videos. video recorder is not even starting 
![image](https://user-images.githubusercontent.com/34208574/125631271-43f23168-192a-4aa7-b043-f0e4d80b57b0.png)

**Comment by Lucifar2** [comment] 2022-05-24 14:51
Please disable WSL2 on Docker desktop and enabled Hyper -V on windows 10. Later restart your machine and docket desktop. Everything will work fine.
