### ISSUE TITLE
 Video-recording files are not saved after stopping the container

### ISSUE THREAD

**Issue by BobrovPavel** [aerokube/selenoid#1088] opened 2021-04-14 09:50 UTC
Hi. I updated my docker for windows (it now uses WSL 2 instead of Hyper-V) and my video recordings stopped saving to `C:\Users\<user>\.aerokube\selenoid\video`
I still use Configuration Manager and do not change any default settings, but now this feature does not work for me. Perhaps there is some way to solve this problem?

selenoid version

`aerokube/selenoid:1.10.3`

docker version

```
 Version:           20.10.5
 API version:       1.41
```

selenoid/video-recorder docker logs

```
Waiting for display to open...
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.3.0 (Alpine 8.3.0)
  configuration: --prefix=/usr --enable-avfilter --enable-gpl --enable-libx264 --enable-static --enable-small --disable-ffplay --disable-ffprobe --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-w32threads --disable-alsa --disable-audiotoolbox --disable-cuda --disable-cuvid --disable-d3d11va --disable-dxva2 --disable-nvenc --disable-vaapi --disable-vdpau --disable-videotoolbox --disable-librtmp --disable-devices --enable-indev=xcbgrab --disable-debug
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[x11grab @ 0x55e0708b2100] Cannot get the image data event_error: response_type:0 error_code:128 sequence:9 resource_id:4194304 minor_code:4 major_code:130.
[x11grab @ 0x55e0708b2100] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, x11grab, from '172.18.0.4:99':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1080, 12 fps, 1000k tbr, 1000k tbn, 1000k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x7fc8a402f300] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7fc8a402f300] profile High, level 4.0
[libx264 @ 0x7fc8a402f300] 264 - core 152 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=9 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=12 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/data/selenoid7c64aebc364185dff9e95ccd7e0c595e.mp4':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 1920x1080, q=-1--1, 12 fps, 12288 tbn, 12 tbc
    Metadata:
      encoder         : Lavc58.54.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=    8 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
frame=   15 fps= 14 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
frame=   21 fps= 13 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
frame=   28 fps= 13 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
frame=   34 fps= 13 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
frame=   40 fps= 13 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
frame=   47 fps= 12 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
frame=   54 fps= 12 q=26.0 size=       0kB time=-00:00:00.16 bitrate=N/A speed=N/A    
frame=   60 fps= 12 q=26.0 size=       0kB time=00:00:00.33 bitrate=   1.2kbits/s speed=0.0688x    
frame=   66 fps= 12 q=26.0 size=       0kB time=00:00:00.83 bitrate=   0.5kbits/s speed=0.156x    
frame=   73 fps= 12 q=26.0 size=       0kB time=00:00:01.41 bitrate=   0.3kbits/s speed=0.239x    
frame=   80 fps= 12 q=26.0 size=       0kB time=00:00:02.00 bitrate=   0.2kbits/s speed=0.307x    
frame=   87 fps= 12 q=26.0 size=       0kB time=00:00:02.58 bitrate=   0.1kbits/s speed=0.364x    
frame=   94 fps= 12 q=26.0 size=       0kB time=00:00:03.16 bitrate=   0.1kbits/s speed=0.413x    
frame=  100 fps= 12 q=26.0 size=       0kB time=00:00:03.66 bitrate=   0.1kbits/s speed=0.448x    
frame=  107 fps= 12 q=26.0 size=       0kB time=00:00:04.25 bitrate=   0.1kbits/s speed=0.485x    
frame=  113 fps= 12 q=26.0 size=       0kB time=00:00:04.75 bitrate=   0.1kbits/s speed=0.513x    
frame=  120 fps= 12 q=26.0 size=       0kB time=00:00:05.33 bitrate=   0.1kbits/s speed=0.542x    
frame=  127 fps= 12 q=26.0 size=       0kB time=00:00:05.91 bitrate=   0.1kbits/s speed=0.568x    
frame=  133 fps= 12 q=26.0 size=       0kB time=00:00:06.41 bitrate=   0.1kbits/s speed=0.587x    
frame=  134 fps= 12 q=-1.0 Lsize=      70kB time=00:00:10.91 bitrate=  52.2kbits/s speed=0.963x    
video:67kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.506962%
```
selenoid docker logs
```
2021/04/14 09:17:51 [-] [NEW_REQUEST] [unknown] [172.18.0.1]

2021/04/14 09:17:51 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.18.0.1]

2021/04/14 09:17:51 [2] [LOCATING_SERVICE] [chrome] [88.0]

2021/04/14 09:17:51 [2] [USING_DOCKER] [chrome] [88.0]

2021/04/14 09:17:51 [2] [CREATING_CONTAINER] [selenoid/chrome:88.0]

2021/04/14 09:17:52 [2] [STARTING_CONTAINER] [selenoid/chrome:88.0] [1bb72cba2e3e3b3cb99a701856714c0707bf9fad05ac0a280cfe784239878bc8]

2021/04/14 09:17:52 [2] [CONTAINER_STARTED] [selenoid/chrome:88.0] [1bb72cba2e3e3b3cb99a701856714c0707bf9fad05ac0a280cfe784239878bc8] [0.36s]

2021/04/14 09:17:52 [2] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]

2021/04/14 09:17:52 [2] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [68552cb5e942331ec6756a8aea7f027052ecbbc28e937698605820a17ef46354]

2021/04/14 09:17:52 [2] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [68552cb5e942331ec6756a8aea7f027052ecbbc28e937698605820a17ef46354] [0.50s]

2021/04/14 09:17:52 [2] [SERVICE_STARTED] [selenoid/chrome:88.0] [1bb72cba2e3e3b3cb99a701856714c0707bf9fad05ac0a280cfe784239878bc8] [0.00s]

2021/04/14 09:17:52 [2] [PROXY_TO] [1bb72cba2e3e3b3cb99a701856714c0707bf9fad05ac0a280cfe784239878bc8] [http://172.18.0.4:4444/]

2021/04/14 09:17:52 [2] [SESSION_ATTEMPTED] [http://172.18.0.4:4444/] [1]

2021/04/14 09:17:53 [2] [SESSION_CREATED] [b6aec156434379e3f8c9ed2bdf989f9b] [1] [1.16s]

2021/04/14 09:18:03 [13] [SESSION_DELETED] [b6aec156434379e3f8c9ed2bdf989f9b]

2021/04/14 09:18:03 [2] [STOPPING_VIDEO_CONTAINER] [68552cb5e942331ec6756a8aea7f027052ecbbc28e937698605820a17ef46354]

2021/04/14 09:18:04 [2] [REMOVING_CONTAINER] [68552cb5e942331ec6756a8aea7f027052ecbbc28e937698605820a17ef46354]

2021/04/14 09:18:04 [2] [FAILED_TO_REMOVE_CONTAINER] [68552cb5e942331ec6756a8aea7f027052ecbbc28e937698605820a17ef46354] [Error response from daemon: removal of container 68552cb5e942331ec6756a8aea7f027052ecbbc28e937698605820a17ef46354 is already in progress]

2021/04/14 09:18:04 [2] [REMOVING_CONTAINER] [1bb72cba2e3e3b3cb99a701856714c0707bf9fad05ac0a280cfe784239878bc8]

2021/04/14 09:18:05 [2] [CONTAINER_REMOVED] [1bb72cba2e3e3b3cb99a701856714c0707bf9fad05ac0a280cfe784239878bc8]

2021/04/14 09:18:05 [2] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoidcef2023ba7aafa2830e10c35b62ec1cb.mp4 to /opt/selenoid/video/b6aec156434379e3f8c9ed2bdf989f9b.mp4: rename /opt/selenoid/video/selenoidcef2023ba7aafa2830e10c35b62ec1cb.mp4 /opt/selenoid/video/b6aec156434379e3f8c9ed2bdf989f9b.mp4: no such file or directory]
```

chrome docker logs
```
E: [pulseaudio] client-conf-x11.c: xcb_connection_has_error() returned true
2021/04/14 09:20:38 [INIT] [Listening on :7070]
xcb_connection_has_error() returned true
21
Waiting X server...
Logging to: /dev/null
Waiting X server...
Waiting X server...
Starting ChromeDriver 88.0.4324.27 (6347fe8bf1e48bd0c54d07dc55ca011cf40861c9-refs/branch-heads/4324@{#450}) on port 4444
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

 --- x11vnc loop: 1 ---

 --- x11vnc loop: waiting for: 227
```
selenoid/video-recorder inspect

[inspect.log](https://github.com/aerokube/selenoid/files/6309882/inspect.log)

**Comment by vania-pooh** [comment] 2021-04-14 10:26
Duplicate of https://github.com/aerokube/cm/issues/293.

**Closed** 2021-04-14 10:26 UTC
