### ISSUE TITLE
unknown error: Chrome failed to start: crashed

### ISSUE THREAD

**Issue by regiewby** [aerokube/selenoid#1110] opened 2021-06-05 01:21 UTC
Hi,
i'm trying to use selenoid in Mac M1 chip and i always get problem while execute the test script.
but when i move to Mac for intel, it absolutely works.

<img width="1058" alt="Screen Shot 2021-06-05 at 08 19 09" src="https://user-images.githubusercontent.com/63327727/120875589-c4c74900-c5d6-11eb-9f8c-355f4ffe00cc.png">

<img width="747" alt="Screen Shot 2021-06-05 at 08 19 16" src="https://user-images.githubusercontent.com/63327727/120875594-cabd2a00-c5d6-11eb-90cf-50618f455aa1.png">

**Comment by vania-pooh** [comment] 2021-06-05 07:44
Duplicate of #1109.

**Closed by vania-pooh** 2021-06-05 07:44 UTC
