### ISSUE TITLE
process terminates with panic on rhel6 running selenoid using binaries

### ISSUE THREAD

**Issue by amitverma12** [aerokube/selenoid#666] opened 2019-02-06 19:10 UTC
Hi, 

I am trying to run selenoid using binaries on RHEL6.5 machine. Selenoid is running fine but when my test tries to get a browser connection, the process is terminated.  Tried for both chrome & firefox.
Please help resolve this issue.

```
[user@vmname ~]$   ./cm selenoid start
> Docker is not supported - using binaries...
> Selenoid is already downloaded
> Selenoid is already configured
> Starting Selenoid...
> Successfully started Selenoid
[user@vmname ~]$ 2019/02/05 22:19:02 [-] [INIT] [Loading configuration files...]
2019/02/05 22:19:02 [-] [INIT] [Loaded configuration from /home/user/.aerokube/selenoid/browsers.json]
2019/02/05 22:19:02 [-] [INIT] [Logs Dir: /home/user/.aerokube/selenoid/logs]
2019/02/05 22:19:02 [-] [INIT] [Timezone: Local]
2019/02/05 22:19:02 [-] [INIT] [Listening on :4444]
2019/02/05 22:19:27 [-] [NEW_REQUEST] [unknown] [127.0.0.1]
2019/02/05 22:19:27 [-] [NEW_REQUEST_ACCEPTED] [unknown] [127.0.0.1]
2019/02/05 22:19:27 [0] [LOCATING_SERVICE] [chrome] []
2019/02/05 22:19:27 [-] [DEFAULT_VERSION] [Using default version: latest]
2019/02/05 22:19:27 [0] [USING_DRIVER] [chrome] [latest]
2019/02/05 22:19:27 [0] [ALLOCATING_PORT]
2019/02/05 22:19:27 [0] [ALLOCATED_PORT] [43416]
2019/02/05 22:19:27 [0] [STARTING_PROCESS] [[/home/user/.aerokube/selenoid/chromedriver --whitelisted-ips='' --verbose --port=43416]]
2019/02/05 22:19:57 [0] [TERMINATING_PROCESS] [2272]
2019/02/05 22:19:57 http: panic serving 127.0.0.1:44074: interface conversion: io.Writer is nil, not *os.File
goroutine 22 [running]:
net/http.(*conn).serve.func1(0xc0002d4e60)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1746 +0xd0
panic(0x767360, 0xc000238a80)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/panic.go:513 +0x1b9
github.com/aerokube/selenoid/service.(*Driver).stopProcess(0xc0002e4f00, 0xc0000f94a0)
        /home/travis/gopath/src/github.com/aerokube/selenoid/service/driver.go:92 +0x3d5
github.com/aerokube/selenoid/service.(*Driver).StartWithCancel(0xc0002e4f00, 0xc0002facc0, 0x6, 0x0)
        /home/travis/gopath/src/github.com/aerokube/selenoid/service/driver.go:75 +0xdf8
main.create(0x83a460, 0xc0003000e0, 0xc000125200)
        /home/travis/gopath/src/github.com/aerokube/selenoid/selenoid.go:174 +0x80b
net/http.HandlerFunc.ServeHTTP(0x7eb6f8, 0x83a460, 0xc0003000e0, 0xc000125200)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964 +0x44
main.post.func1(0x83a460, 0xc0003000e0, 0xc000125200)
        /home/travis/gopath/src/github.com/aerokube/selenoid/main.go:308 +0x9e
net/http.HandlerFunc.ServeHTTP(0xc0002a1ba0, 0x83a460, 0xc0003000e0, 0xc000125200)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964 +0x44
github.com/aerokube/selenoid/protect.(*Queue).Protect.func1(0x83a460, 0xc0003000e0, 0xc000125200)
        /home/travis/gopath/src/github.com/aerokube/selenoid/protect/queue.go:76 +0x3c2
net/http.HandlerFunc.ServeHTTP(0xc000237360, 0x83a460, 0xc0003000e0, 0xc000125200)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964 +0x44
github.com/aerokube/selenoid/protect.(*Queue).Check.func1(0x83a460, 0xc0003000e0, 0xc000125200)
        /home/travis/gopath/src/github.com/aerokube/selenoid/protect/queue.go:53 +0x9a
net/http.HandlerFunc.ServeHTTP(0xc000237380, 0x83a460, 0xc0003000e0, 0xc000125200)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964 +0x44
github.com/aerokube/selenoid/protect.(*Queue).Try.func1(0x83a460, 0xc0003000e0, 0xc000125200)
        /home/travis/gopath/src/github.com/aerokube/selenoid/protect/queue.go:35 +0xd4
net/http.HandlerFunc.ServeHTTP(0xc0002373a0, 0x83a460, 0xc0003000e0, 0xc000125200)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000338300, 0x83a460, 0xc0003000e0, 0xc000125200)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:2361 +0x127
main.handler.func1(0x83a460, 0xc0003000e0, 0xc000125200)
        /home/travis/gopath/src/github.com/aerokube/selenoid/main.go:370 +0x157
net/http.HandlerFunc.ServeHTTP(0x7eb720, 0x83a460, 0xc0003000e0, 0xc000125200)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000191f20, 0x83a460, 0xc0003000e0, 0xc000125200)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc000306270, 0x83a460, 0xc0003000e0, 0xc000125200)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0002d4e60, 0x83a7e0, 0xc0002e2ac0)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:2851 +0x2f5
2019/02/05 22:19:57 [-] [NEW_REQUEST] [unknown] [127.0.0.1]
2019/02/05 22:19:57 [-] [NEW_REQUEST_ACCEPTED] [unknown] [127.0.0.1]
```

**Comment by vania-pooh** [comment] 2019-02-07 10:13
@amitverma12 duplicate of #665.

**Closed by vania-pooh** 2019-02-07 10:13 UTC

**Comment by amitverma12** [comment] 2019-02-07 13:08
@vania-pooh - Thank you !
